### ISSUE TITLE
Cannot start line with ‘On’ in reply

### ISSUE THREAD

**Issue by sorbits** [github/email_reply_parser#23]
A bottom-quoted email that has a line in the reply start with “On” will discard that line and everything below it.

The code responsible can be found on [line #87-90 of email_reply_parser.rb](https://github.com/github/email_reply_parser/blob/master/lib/email_reply_parser.rb#L87-L90):

```
if text =~ /^(On\s(.+)wrote:)$/nm
  # Remove all new lines from the reply header.
  text.gsub! $1, $1.gsub("\n", " ")
end
```

An example email that shows the issue follows:

```
On your remote host you can run:

     telnet 127.0.0.1 52698

This should connect to TextMate (on your Mac, via the tunnel). If that 
fails, the tunnel is not working.

On 9 Jan 2014, at 2:47, George Plymale wrote:

> I am having an odd issue wherein suddenly port forwarding stopped 
> working in a particular scenario for me.  By default I have ssh set to 
> use the following config (my ~/.ssh/config file):
> […]
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/textmate/rmate/issues/29
```

**Comment by gsdean** [comment]
FWIW zapier ported this, and just fixed the same issue 
https://github.com/zapier/email-reply-parser/pull/12

**Comment by mattyoho** [comment]
This issue has been fixed, I believe, thanks.
