### ISSUE TITLE
Markdown not parsed in emails

### ISSUE THREAD

**Issue by pjrobertson** [github/email_reply_parser#25]
If you send an email reply in markdown (e.g. with `backticks` or some kind of:
- list
- and stuff )

It is not converted into Markdown on the actual site.
Moreover, editing the comment/reply on Github still does not convert the email to markdown

**Comment by pb-cdunn** [comment]
@pjrobertson, did you get a response? This remains a real issue.

**Comment by pjrobertson** [comment]
I never got round to sending an email to support@ ...
