### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by jimgraham** [github/email_reply_parser#37]
Are there plans to support other languages in the `On, wrote` regex?

One of our collaborators responded with the following email:

```
Just saw that when it stays in the valve panel, and the next measurement is done, it updates. Just as Jim expected. 

Op 13 jan. 2015 om 17:02 heeft "Jim Graham" <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven: 

[previous comment]

— 
Reply to this email directly or view it on GitHub<https://github.com/Capilix/Capella/issues/117>.
```

Although this email is in English, his email client is configured in Dutch, so it wrote `Op 13 jan. 2015 om 17:02 heeft "Jim Graham" `

**Comment by technoweenie** [comment]
I'd be in favor of a refactoring that made it easier to extend based on your custom needs.  If the core gem could support more languages beyond english, that'd be great.  We have no plans on adding this support now though.

**Comment by jimgraham** [comment]
Thanks for the response. I don't have custom needs, it was more for duplication of test within our Github Issues.
