### ISSUE TITLE
Question: Python port

### ISSUE THREAD

**Issue by antonagestam** [github/email_reply_parser#42]
Hi,

Just wanted to let you know that I'm working on a Python port of this package, if you want to you can link to it from here. I've included your LICENSE file :v:

**Comment by technoweenie** [comment]
Cool, just be sure to change the copyright notice in the license :)

**Comment by antonagestam** [comment]
Here's the link project: https://github.com/antonagestam/python-email-reply-parser

What should I change the copyright notice to? I kinda consider it a version of the original since a lot of comments and tests are identical.

> The above copyright notice and this permission notice shall be included in
> all copies or substantial portions of the Software.

**Comment by Onumis** [comment]
@antonagestam do note that pythonists are already quite well served with this: https://github.com/mailgun/talon

**Comment by farlee2121** [comment]
Zapier also made a port of this library to python https://github.com/zapier/email-reply-parser
